Feature/shelby financials account grouping2
KingdomFirst/RockBlocks pull request #138
Opened 2023-05-16 16:02 UTC by guymaness2

### Description 

##### What does the change add or fix?

Added capability of separating transaction fees out into separate debit/credit lines. Also added a block setting to control grouping of accounts in the resulting Excel file.

**New Settings:**
Batch to Journal and Batches to Journal Block
* GL Account Grouping - Determines if debit and/or credit lines should be grouped and summed by GL account in the export file  

**New Attributes:**
Financial Gateway Attributes:  
* Shelby Financials Export > Gateway Fee Processing - Sets how the gateway should process fees
* Shelby Financials Export > Default Fee Account - Sets the default account for transaction fees
  
Financial Account Attributes:
* Shelby Financials Export > Transaction Fee Account - Sets the account to use for transaction fees

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

* Added support for handling transaction fees to FinancialGateways and FinancialAccounts
* Added block settings to group accounts in resulting Excel file. 

---------

### Requested By

##### Who reported, requested, or paid for the change?

Simple Donation

---------

### Screenshots

##### Does this update or add options to the block UI?

New Financial Gateway Attributes:  
![image](https://github.com/KingdomFirst/RockBlocks/assets/7374281/4e62a546-59fe-421b-84fa-0c521f291b1d)
  
New Financial Account Attribute:  
![image](https://github.com/KingdomFirst/RockBlocks/assets/7374281/d9df540c-da26-4d8c-ae26-6c9682e791a9)  
  
New block setting for Batch To Journal and Batches To Journal blocks:  
![image](https://github.com/KingdomFirst/RockBlocks/assets/7374281/d4ebbd45-8f4d-40b0-861c-6185373ecd9c)
  
---------

### Change Log

##### What files does it affect?

* ShelbyFinancials/BatchToJournal.ascx.cs
* ShelbyFinancials/BatchesToJournal.ascx.cs
  
---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

Has dependency on https://github.com/KingdomFirst/RockAssemblies/pull/123

2023-05-16 17:11 UTC, guymaness2 commented on ShelbyFinancials/BatchToJournal.ascx.cs
> +        Description = "Determines if debit and/or credit lines should be grouped and summed by GL account in the export file.",
```suggestion
        Description = "Determines if debit and/or credit lines should be grouped and summed by GL account in the export file. NOTE: Unique Projects, Regions, Funds, etc. may result in multiple lines even if account is grouped.",
```

2023-05-16 17:14 UTC, guymaness2 commented on ShelbyFinancials/BatchesToJournal.ascx.cs
> +        Description = "Determines if debit and/or credit lines should be grouped and summed by GL account in the export file.",
```suggestion
        Description = "Determines if debit and/or credit lines should be grouped and summed by GL account in the export file. NOTE: Unique Projects, Regions, Funds, etc. may result in multiple lines even if account is grouped.",
```

2023-05-16 17:24 UTC, guymaness2 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">4</span> | **GL Account Grouping** Determ
Add detailed note describing what fields are grouped by for debit grouping, credit grouping, and financial account grouping

2023-05-16 17:25 UTC, guymaness2 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">3</span> | **GL Account Grouping** Determ
Add detailed note describing what fields are grouped by for debit grouping, credit grouping, and financial account grouping

2023-05-16 17:27 UTC, guymaness2 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">5</span> | **Enable Debug** Outputs the o
```suggestion
| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">6</span> | **Enable Debug** Outputs the object graph to help create your Lava syntax |
```

2023-05-16 17:29 UTC, nateh777 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">1</span> | **Gateway Fee Processing** How
```suggestion
| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">1</span> | **Gateway Fee Processing** How should the Shelby Financials plugin process transaction fees? DEFAULT: No special handling of transaction fees will be performed. NET DEBIT: Add credit entries for any transaction fees and use net amount (amount - transaction fees) for debit account entries. GROSS DEBIT: Debit account entries are left untouched (gross) and new debit and credit entries will be added for any transaction fees. NOTE: Both Net Debit and Gross Debit require a Fee Account attribute be set on either the financial gateway or financial account. |
```

2023-05-16 17:30 UTC, nateh777 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">1</span> | **Gateway Fee Processing** How
Can you also try to see if you can make a bulleted list out of the items? If it isn't possible in a table that is fine, but I just want to try.

2023-05-16 22:23 UTC, guymaness2 commented
@nateh777 should be ready for merge

2023-05-17 15:20 UTC, nateh777 requested changes
Minor changes needed for documentation otherwise changes look good.

2023-05-17 15:20 UTC, nateh777 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">3</span> | **GL Account Grouping** Determ
"Revenue Account Sub Account" should just be "Revenue Account Sub"

2023-05-17 15:20 UTC, nateh777 commented on ShelbyFinancials/ReadMe.md
> +| <span style="width: 3em; height: 3em; line-height: 3em; background: #d21919; border-radius: 100%; color: white; text-align: center; display: inline-block;">3</span> | **GL Account Grouping** Determ
"Revenue Account Sub Account" should just be "Revenue Account Sub"

2023-05-17 16:50 UTC, nateh777 approved these changes

2023-05-17 16:50 UTC, merged